language: node_js

sudo: required

services:
  - docker

cache:
  directories:
  - ${HOME}/.cache
  - ${HOME}/.m2
  - ${HOME}/google-cloud-sdk

script:
  - ./ci/build.sh

env:
  global:
  - PATH=${HOME}/google-cloud-sdk/bin:$PATH
  - CLOUDSDK_CORE_DISABLE_PROMPTS=1